// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ6rJGgL7jwI4P5pV-jChuZxJidBqluXA',
    appId: '1:456187198402:web:464f9803fcb715217d345b',
    messagingSenderId: '456187198402',
    projectId: 'safar-sync',
    authDomain: 'safar-sync.firebaseapp.com',
    storageBucket: 'safar-sync.firebasestorage.app',
    measurementId: 'G-LL9GXP49XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6wXBd_0LYj19kyPbD8KQ8Fb3cTKWwZoE',
    appId: '1:456187198402:android:655a05fdfe903c8f7d345b',
    messagingSenderId: '456187198402',
    projectId: 'safar-sync',
    storageBucket: 'safar-sync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZdbgxTAq85fHVO77vFJCInXkHdr-vJWU',
    appId: '1:456187198402:ios:04ffc4258e7124657d345b',
    messagingSenderId: '456187198402',
    projectId: 'safar-sync',
    storageBucket: 'safar-sync.firebasestorage.app',
    iosBundleId: 'com.example.safarSync',
  );
}
